export const categoriesHU = [
  { id: 'brakes', name: 'Fékek', description: 'Kiváló minőségű fékkomponenseket szállítunk minden járműtípushoz – féktárcsák, fékbetétek és komplett fékrendszerek.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/x2n4ufrn_bremsen.jpg' },
  { id: 'filters', name: 'Olaj és Szűrők', description: 'Légszűrők, olajszűrők, üzemanyagszűrők – rendelkezünk a megfelelő szűrőkkel az optimális motorteljesítményhez.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/ox4a7k60_Filter.jpeg' },
  { id: 'chassis', name: 'Futómű', description: 'Lengéscsillapítók, rugók, lengőkarok és további futómű-komponensek ellenőrzött minőségben.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/hvcgzlb3_fahrwerk%20%282%29.jpg' },
  { id: 'electrical', name: 'Elektromos', description: 'Akkumulátorok, indítómotorok, generátorok és elektromos komponensek – szakértői tanácsadás.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/hb1f5eac_elektrik.jpg' },
  { id: 'lighting', name: 'Világítás', description: 'Fényszórók, izzók, hátsó lámpák – optimális láthatóság nappal és éjjel. LED, Xenon vagy Halogén.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/027lpw4v_beleuchtung.jpg' },
  { id: 'exhaust', name: 'Kipufogó', description: 'Kipufogó dobok, katalizátorok, részecskeszűrők – tiszta kipufogógáz és optimális teljesítmény.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/gghcbeg0_Auspuff.jpeg' },
  { id: 'clutch', name: 'Kuplung', description: 'Kuplung készletek, kéttömegű lendkerekek, kioldócsapágyak – sima sebességváltáshoz.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/nakw9ewc_kupplung.webp' },
  { id: 'engine', name: 'Motor', description: 'Hengerfej tömítések, fogasszíjak, vezérlőláncok, vízpumpák – megbízható motorhoz.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/akowp90d_Motor.jpeg' },
  { id: 'body', name: 'Karosszéria', description: 'Külső tükrök, ajtókilincsek, lökhárítók, sárvédők – tökéletes megjelenés és funkcionalitás.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/knk1i0xe_karosserie.webp' },
  { id: 'drivetrain', name: 'Hajtáslánc', description: 'Hajtótengelyek, csuklók, kardántengelyek – erőteljes és megbízható erőátvitel. Kiváló minőségű hajtáslánc-komponensek OEM minőségben.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/qe7ipe0n_Antrieb.jpeg' },
  { id: 'climate', name: 'Klíma és Fűtés', description: 'Klímakompresszorok, kondenzátorok, fűtőventilátorok – kellemes hőmérséklet minden évszakban.', image: 'https://customer-assets.emergentagent.com/job_autoberatung/artifacts/idk0bzb2_heizung.png' },
  { id: 'others', name: 'Egyéb', description: 'Ablaktörlő lapátok, gumiabroncsok, vonóhorgok és még sok más – minden, amire szüksége van.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/qoza0hlx_sonstige.jpg' }
];

export const categoriesPL = [
  { id: 'brakes', name: 'Hamulce', description: 'Dostarczamy wysokiej jakości komponenty hamulcowe dla wszystkich typów pojazdów – tarcze hamulcowe, klocki hamulcowe i kompletne systemy hamulcowe.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/x2n4ufrn_bremsen.jpg' },
  { id: 'filters', name: 'Olej i Filtry', description: 'Filtry powietrza, filtry oleju, filtry paliwa – mamy odpowiednie filtry dla optymalnej wydajności silnika.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/ox4a7k60_Filter.jpeg' },
  { id: 'chassis', name: 'Podwozie', description: 'Amortyzatory, sprężyny, wahacze i inne komponenty podwozia w sprawdzonej jakości.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/hvcgzlb3_fahrwerk%20%282%29.jpg' },
  { id: 'electrical', name: 'Elektryka', description: 'Akumulatory, rozruszniki, alternatory i komponenty elektryczne – fachowe doradztwo.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/hb1f5eac_elektrik.jpg' },
  { id: 'lighting', name: 'Oświetlenie', description: 'Reflektory, żarówki, światła tylne – optymalna widoczność w dzień i w nocy. LED, Xenon lub Halogen.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/027lpw4v_beleuchtung.jpg' },
  { id: 'exhaust', name: 'Układ wydechowy', description: 'Tłumiki, katalizatory, filtry cząstek stałych – czyste spaliny i optymalna wydajność.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/gghcbeg0_Auspuff.jpeg' },
  { id: 'clutch', name: 'Sprzęgło', description: 'Zestawy sprzęgła, dwumasowe koła zamachowe, łożyska – dla płynnej zmiany biegów.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/nakw9ewc_kupplung.webp' },
  { id: 'engine', name: 'Silnik', description: 'Uszczelki głowicy, paski rozrządu, łańcuchy rozrządu, pompy wody – dla niezawodnego silnika.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/akowp90d_Motor.jpeg' },
  { id: 'body', name: 'Nadwozie', description: 'Lusterka boczne, klamki, zderzaki, błotniki – dla idealnego wyglądu i funkcjonalności.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/knk1i0xe_karosserie.webp' },
  { id: 'drivetrain', name: 'Napęd', description: 'Półosie, przeguby, wały napędowe – dla mocnego i niezawodnego przenoszenia mocy. Wysokiej jakości komponenty napędowe w jakości OEM.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/qe7ipe0n_Antrieb.jpeg' },
  { id: 'climate', name: 'Klimatyzacja i Ogrzewanie', description: 'Sprężarki klimatyzacji, skraplacze, dmuchawy ogrzewania – dla przyjemnej temperatury przez cały rok.', image: 'https://customer-assets.emergentagent.com/job_autoberatung/artifacts/idk0bzb2_heizung.png' },
  { id: 'others', name: 'Pozostałe', description: 'Wycieraczki, opony, haki holownicze i wiele więcej – wszystko, czego potrzebujesz do pojazdu.', image: 'https://customer-assets.emergentagent.com/job_7c9c200c-91a8-481c-82f7-30f6f659281a/artifacts/qoza0hlx_sonstige.jpg' }
];
